# Generated by Django 5.1.3 on 2024-11-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_readbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadBook',
        ),
    ]
